# Generated by Django 3.0.5 on 2020-04-18 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SongGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(help_text='그룹 이름 (애니메이션 제목/보컬로이드)', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name_origin', models.CharField(help_text='노래 제목 (일본어)', max_length=100)),
                ('song_name_korean', models.CharField(help_text='노래 제목 (한국어)', max_length=100)),
                ('singer', models.CharField(help_text='가수(프로듀서)', max_length=20)),
                ('tj', models.IntegerField(help_text='TJ 노래방 번호', null=True)),
                ('ky', models.IntegerField(help_text='KY 노래방 번호', null=True)),
                ('dam', models.IntegerField(help_text='DAM 노래방 번호', null=True)),
                ('uga', models.IntegerField(help_text='UGA 노래방 번호', null=True)),
                ('joy', models.IntegerField(help_text='Joy Sounds 노래방 번호', null=True)),
                ('lyrics', models.TextField(help_text='가사', null=True)),
                ('group', models.ForeignKey(help_text='그룹 (애니메이션 제목/보컬로이드)', on_delete=django.db.models.deletion.CASCADE, to='songbook.SongGroup')),
            ],
        ),
    ]
